use enumset::EnumSetType;
use serde::{Deserialize, Serialize};

#[derive(Debug, Hash, Deserialize, Serialize, EnumSetType)]
#[enumset(serialize_repr = "list")]
#[allow(clippy::enum_variant_names)]
pub enum Capability {
    AutoEmptyDockAutoEmptyIntervalControlCapability,
    AutoEmptyDockManualTriggerCapability,
    BasicControlCapability,
    CameraLightControlCapability,
    CarpetModeControlCapability,
    CarpetSensorModeControlCapability,
    CollisionAvoidantNavigationControlCapability,
    CombinedVirtualRestrictionsCapability,
    ConsumableMonitoringCapability,
    CurrentStatisticsCapability,
    DoNotDisturbCapability,
    FanSpeedControlCapability,
    GoToLocationCapability,
    HighResolutionManualControlCapability,
    KeyLockCapability,
    LocateCapability,
    ManualControlCapability,
    MapResetCapability,
    MapSegmentEditCapability,
    MapSegmentRenameCapability,
    MapSegmentationCapability,
    MapSnapshotCapability,
    MappingPassCapability,
    MopDockCleanManualTriggerCapability,
    MopDockDryManualTriggerCapability,
    MopDockMopAutoDryingControlCapability,
    MopDockMopWashTemperatureControlCapability,
    MopExtensionControlCapability,
    MopExtensionFurnitureLegHandlingControlCapability,
    MopTwistControlCapability,
    ObstacleAvoidanceControlCapability,
    ObstacleImagesCapability,
    OperationModeControlCapability,
    PendingMapChangeHandlingCapability,
    PersistentMapControlCapability,
    PetObstacleAvoidanceControlCapability,
    QuirksCapability,
    SpeakerTestCapability,
    SpeakerVolumeControlCapability,
    TotalStatisticsCapability,
    VoicePackManagementCapability,
    WaterUsageControlCapability,
    WifiConfigurationCapability,
    WifiScanCapability,
    ZoneCleaningCapability,
}
